packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  puppeteer: set this to true or false
  sharp: true
  workerd: set this to true or false
